server:
  port: 9011
spring:
  application:
    name: tensquare‐manager #指定服务名
#instance为线上跨域访问做准备
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
    instance:
      prefer-ip-address: true
#每个服务都可以写为key/value
zuul:
  routes:
    tensquare-gathering: #服务名称
      path: /gathering/** #配置请求URL的请求规则
      serviceId: tensquare-gathering #指定Eureka注册中心中的服务id
    tensquare-base: #服务名称
      path: /base/** #配置请求URL的请求规则
      serviceId: tensquare-base #指定Eureka注册中心中的服务id
jwt:
  config:
    key: text