server:
  port: 8003
spring:
  rabbitmq:
    host: 192.168.233.10
aliyun:
  sms:
    accessKeyId: LTAI4FpPAnDETsK48hFheX3A
    accessKeySecret: 61DjZDsGg7cltd8eWR1IAfkYOl8EoA
    template_code: SMS_174985627
    sign_name: 灰猴LH